### create users

POST http://localhost:3000/api/users
    Content-Type: application/json

 {
    "name": "Carl",
    "password": "1234"
 }

###

GET http://localhost:3000/api/users


###

POST http://localhost:3000/login

{
   "name": "hej",
   "password": "potatis"
}